// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psqlmodel

var TableNames = struct {
	Cars             string
	Orders           string
	SchemaMigrations string
}{
	Cars:             "cars",
	Orders:           "orders",
	SchemaMigrations: "schema_migrations",
}
