// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psqlmodel

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCars(t *testing.T) {
	t.Parallel()

	query := Cars()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCarsSoftDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsQuerySoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Cars().DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsSliceSoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CarSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Cars().DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CarSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCarsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CarExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Car exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CarExists to return true, but got false.")
	}
}

func testCarsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	carFound, err := FindCar(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if carFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCarsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Cars().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCarsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Cars().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCarsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	carOne := &Car{}
	carTwo := &Car{}
	if err = randomize.Struct(seed, carOne, carDBTypes, false, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}
	if err = randomize.Struct(seed, carTwo, carDBTypes, false, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = carOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = carTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Cars().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCarsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	carOne := &Car{}
	carTwo := &Car{}
	if err = randomize.Struct(seed, carOne, carDBTypes, false, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}
	if err = randomize.Struct(seed, carTwo, carDBTypes, false, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = carOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = carTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func carBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func carAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Car) error {
	*o = Car{}
	return nil
}

func testCarsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Car{}
	o := &Car{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, carDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Car object: %s", err)
	}

	AddCarHook(boil.BeforeInsertHook, carBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	carBeforeInsertHooks = []CarHook{}

	AddCarHook(boil.AfterInsertHook, carAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	carAfterInsertHooks = []CarHook{}

	AddCarHook(boil.AfterSelectHook, carAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	carAfterSelectHooks = []CarHook{}

	AddCarHook(boil.BeforeUpdateHook, carBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	carBeforeUpdateHooks = []CarHook{}

	AddCarHook(boil.AfterUpdateHook, carAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	carAfterUpdateHooks = []CarHook{}

	AddCarHook(boil.BeforeDeleteHook, carBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	carBeforeDeleteHooks = []CarHook{}

	AddCarHook(boil.AfterDeleteHook, carAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	carAfterDeleteHooks = []CarHook{}

	AddCarHook(boil.BeforeUpsertHook, carBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	carBeforeUpsertHooks = []CarHook{}

	AddCarHook(boil.AfterUpsertHook, carAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	carAfterUpsertHooks = []CarHook{}
}

func testCarsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCarsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(carColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCarToManyOrders(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Car
	var b, c Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, orderDBTypes, false, orderColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, orderDBTypes, false, orderColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CarID = a.ID
	c.CarID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Orders().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CarID == b.CarID {
			bFound = true
		}
		if v.CarID == c.CarID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CarSlice{&a}
	if err = a.L.LoadOrders(ctx, tx, false, (*[]*Car)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Orders); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Orders = nil
	if err = a.L.LoadOrders(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Orders); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testCarToManyAddOpOrders(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Car
	var b, c, d, e Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, carDBTypes, false, strmangle.SetComplement(carPrimaryKeyColumns, carColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Order{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, orderDBTypes, false, strmangle.SetComplement(orderPrimaryKeyColumns, orderColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Order{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddOrders(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.CarID {
			t.Error("foreign key was wrong value", a.ID, first.CarID)
		}
		if a.ID != second.CarID {
			t.Error("foreign key was wrong value", a.ID, second.CarID)
		}

		if first.R.Car != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Car != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Orders[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Orders[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Orders().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCarsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCarsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CarSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCarsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Cars().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	carDBTypes = map[string]string{`ID`: `integer`, `CarName`: `character varying`, `DayRate`: `double precision`, `MonthRate`: `double precision`, `Image`: `character varying`, `CreatedBy`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedBy`: `integer`, `UpdatedAt`: `timestamp with time zone`, `DeletedBy`: `integer`, `DeletedAt`: `timestamp with time zone`}
	_          = bytes.MinRead
)

func testCarsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(carPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(carAllColumns) == len(carPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, carDBTypes, true, carPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCarsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(carAllColumns) == len(carPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Car{}
	if err = randomize.Struct(seed, o, carDBTypes, true, carColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, carDBTypes, true, carPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(carAllColumns, carPrimaryKeyColumns) {
		fields = carAllColumns
	} else {
		fields = strmangle.SetComplement(
			carAllColumns,
			carPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CarSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCarsUpsert(t *testing.T) {
	t.Parallel()

	if len(carAllColumns) == len(carPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Car{}
	if err = randomize.Struct(seed, &o, carDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Car: %s", err)
	}

	count, err := Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, carDBTypes, false, carPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Car struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Car: %s", err)
	}

	count, err = Cars().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
