// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psqlmodel

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Cars", testCarsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)
}
